### ISSUE TITLE
Cookie Consent request 

### ISSUE THREAD

**Issue by coulisse** [coulisse/spiderweb#11]
On the site [n8mfn.club ](http://n8mfn.club/)  always requires consent to cookies, even if this has already been given once.

from [kb8pmy@kb8pmy.net](kb8pmy@kb8pmy.net)

**Comment by audric** [comment]
Same here...

**Comment by coulisse** [comment]
Hello
this project is designed to work with secure protocol SSL.
Are you using http instead https ?
If yes is better to switch to https, however if you don't use http could  you the following setting in webapp.py:

     SESSION_COOKIE_SECURE=True,    
to

     SESSION_COOKIE_SECURE=False,   


Waiting for your feedback.


Corrado

**Comment by coulisse** [comment]
Hello 
have you any news?

Thanks
Corrado
