### ISSUE TITLE
No results for callsign search

### ISSUE THREAD

**Issue by glaukos78** [coulisse/spiderweb#29]
Hello,

in the new version something going wrong with callsign search.
Not appear right results.

73 de Yiannis, SV5FRI

**Comment by coulisse** [comment]
I'll check soon

**Comment by coulisse** [comment]
Could you try with new release, please?

Thanks,
 Corrado

**Comment by glaukos78** [comment]
It's working now

Thanks

73 de Yiannis, SV5FRI

**Comment by glaukos78** [comment]
Also when change to plots and callsign page the clock not appear
