### ISSUE TITLE
DXSpider cluster statistic

### ISSUE THREAD

**Issue by s50u** [coulisse/spiderweb#3]
Corrado

According to the TODO.md

> add page with connected nodes

I can provide scripts with an explanation for some DXSpider cluster statistic if you wanted to include them on a new page of spiderweb app?

73 Danilo S50U

**Comment by coulisse** [comment]
Yes sure!
73 Corrado

Il Dom 17 Gen 2021, 08:39 s50u <notifications@github.com> ha scritto:

**Comment by s50u** [comment]
Corrado

please check private email. Thanks for conection nodes I would remove IP's from the list for security reasons.

73 Danilo

**Comment by coulisse** [comment]
Closed with 2.0 versione
