### ISSUE TITLE
Clock not appear on the plot & callsign pages

### ISSUE THREAD

**Issue by glaukos78** [coulisse/spiderweb#30]
The clock not appear on the plot & callsign pages

![image](https://user-images.githubusercontent.com/16499395/214160026-a5d41fb6-3b33-480a-9e68-7868dd681c7c.png)

73 de Yiannis, SV5FRI

**Comment by coulisse** [comment]
Thanks for your test.
Could you check it on stanging branch?

If ok I'll merge to master and I'll make a new release.

Corrado

**Comment by coulisse** [comment]
If you preferr, you can see the version 2.4.1.2 (in stanging) running on my test website [test.i1ubow.it](https://test.iu1bow.it)

**Comment by glaukos78** [comment]
Hi corrado,

I have check your new version and working fine

**Comment by coulisse** [comment]
Released v2.4.1.2

Thanks for your test!
