### ISSUE TITLE
user + password telnet access

### ISSUE THREAD

**Issue by picchiosat** [coulisse/spiderweb#34]
To be able to use telnet access with a user who has set the password
add/edit the following lines to dxtelnet.py

def who(host, port, user):

    WAIT_FOR = b"dxspider >"
    WAIT_PASS = b"password:"
    TIMEOUT = 1
    res = 0
    user = "username"
    password = "your_password"
     try:
         tn = telnetlib.Telnet(host, port, TIMEOUT)
         try:
            tn.read_until(b"login: ", TIMEOUT)
            tn.write(user.encode("ascii") + b"\n")
            tn.read_until(WAIT_PASS, TIMEOUT)
            tn.write(password.encode("ascii") + b"\n")
            res = tn.read_until(WAIT_FOR, TIMEOUT)
            tn.write(b"who\n")
            res = tn.read_until(WAIT_FOR, TIMEOUT)
            tn.write(b"exit\n")

73 de Roby IV3JDV

**Comment by coulisse** [comment]
Could you check if the problem is solve with pre-release v2.4.5.1 ?

Thanks
Corrado
