### ISSUE TITLE
[WARNING] (webapp.py) no data found

### ISSUE THREAD

**Issue by HB9VQQ** [coulisse/spiderweb#37]
I see this warning in webapp.log

[WARNING] (webapp.py) no data found

Disregard?

**Comment by coulisse** [comment]
Hello
It seems that it could not connect to database.

Could you connect manually to databse dxcluster and see if table spot is empty?

**Comment by HB9VQQ** [comment]
Database connection works.

![image](https://user-images.githubusercontent.com/75934980/220901993-0255d085-f914-4a83-9599-e3c1211dfabe.png)

**Comment by HB9VQQ** [comment]
Just to clarify everything seems to work except seeing this warning in the log
https://webcluster.hb9vqq.ch/

**Comment by coulisse** [comment]
Please, change the log level from INFO  to DEBUG in webapp_config_log.ini  and restart spiderweb, in order to have more informations on the log

**Comment by HB9VQQ** [comment]
Done
![image](https://user-images.githubusercontent.com/75934980/221010620-9253df59-804b-47dc-80ec-d4c1413a98ee.png)

**Comment by coulisse** [comment]
I dont' find  errors... I think it is a "false positive", however I'll check better on new release

**Comment by HB9VQQ** [comment]
Did not occure anymore. Closing issue . Thank you
