### ISSUE TITLE
Physically connected callsigns empty

### ISSUE THREAD

**Issue by HB9VQQ** [coulisse/spiderweb#38]
![image](https://user-images.githubusercontent.com/75934980/222804486-9b67a80b-7e4f-4df4-83c2-e198cf32b810.png)

**Comment by efiten** [comment]
Same problem here. How can I fill it with the correct data ?
![image](https://user-images.githubusercontent.com/11015082/223180759-9f63cf51-a7ff-4085-ae39-dd7331ba7cf3.png)

**Comment by coulisse** [comment]
Is your cluster protected by password?

**Comment by coulisse** [comment]
See issue #34

**Comment by coulisse** [comment]
Could you check if the problem is solve with pre-release v2.4.5.1 ?

Thanks
Corrado

**Comment by coulisse** [comment]
Closed with release [v2.5.2](https://github.com/coulisse/spiderweb/releases/tag/v2.5.2)
