### ISSUE TITLE
FT8 Spots shown when Mode Filter "CW" is active

### ISSUE THREAD

**Issue by HB9VQQ** [coulisse/spiderweb#40]
If the CW Mode Filter is active there are still FT8 Spots displayed mainly on the 6m Band 

![image](https://user-images.githubusercontent.com/75934980/235247141-a4b2ec74-4c20-4b46-9379-7c5e390e444e.png)

50.313 is the FT8 QRG on the 6m Band, which needs to be excluded when the CW filter is enabled

**Comment by DocViper666** [comment]
You can assign modes by changing the 
`/cfg/modes.json`
FT8 is seen as "within the CW" range. You would need to have a range for CW lower and higher seperatly - and assign the FT8 to digi. But I have not tried that myself.

**Comment by coulisse** [comment]
I'll change `modes.json` in order to check all ft8 frequencies  are in DIGI modes

**Comment by coulisse** [comment]
Closed with 4.2.5 release
