### ISSUE TITLE
Conversion of band.pl (mojo branch) causes JSONException

### ISSUE THREAD

**Issue by DocViper666** [coulisse/spiderweb#43]
Dear OM,

I have your great web frontend for our newly created DXspider Cluster setup. 
https://dxcluster.oevsv.at/

Todo so we have packed it into a docker compose (I will publish it later this week) that includes the dxspider, a mariadb and your webinterface. So every service has it's own container.
Anyhow I have shared the spider/data folder to allow this:

`python /app/lib/get_dxcluster_modes.py /spider/data/bands.pl`

Which results in this
```
08/06/2023 03:25:08 [INFO]: RDxSpider band file conversion starting...
08/06/2023 03:25:08 [ERROR]: An exception of type JSONDecodeError occurred. Arguments:
("Expecting ',' delimiter: line 1 column 2368 (char 2367)",)
08/06/2023 03:25:08 [ERROR]: /spider/data/bands.pl
08/06/2023 03:25:08 [ERROR]: error on parsing input file
```

I have looked into the new file version of bands.pl (mojo branch).
[http://www.dxcluster.org/gitweb/gitweb.cgi?p=spider.git;a=blob;f=data/bands.pl;h=1bd60f671b6d0bc70268ad20ebcba7874df3038e;hb=f43ac25669a7b9368d9537eed2043a864a906303]

I think the issue is that "hf" and "vhf" don't have single quotes. Not sure why this is done like that...

`		  'pmruhf' => bless ( { band => [425000, 430000, 440000, 471000],
							  }, 'Bands'),
		   hf => bless ( { band => [1800, 29999], }, 'Bands'), 
		   vhf => bless ( { band => [30000, 299999], }, 'Bands'), 
		 );`

I guess that is something that needs fixing on the DXspider side. Just to let you know. 

73 Joe

**Comment by coulisse** [comment]
Ok, thanks for your informations. Please share your website :-)
