### ISSUE TITLE
Please add a filter - reset button to the filter pane

### ISSUE THREAD

**Issue by DocViper666** [coulisse/spiderweb#44]
On the spot page when one selects a filter e.g. VHF and hits the filter button this works fine.

There is no easy way to remove the filter option. One has to (Crtl - Mouseclick) in the list to select all bands again to reset the filter.
Please add a "clear filter" or "Show all" button to restore the default view.

Thanks a lot.
Joe, OE5JFE

**Comment by coulisse** [comment]
Closed with 4.2.5 release
