### ISSUE TITLE
Error On raspi install

### ISSUE THREAD

**Issue by 9M2PJU** [coulisse/spiderweb#49]
<img width="715" alt="image" src="https://github.com/coulisse/spiderweb/assets/991353/59415d72-4b91-45d4-9477-302ed3edafee">

**Comment by 9M2PJU** [comment]
![image](https://github.com/coulisse/spiderweb/assets/991353/91d13f84-10f1-465d-b667-c5b54b2b01cc)

**Comment by DocViper666** [comment]
Hi Piju,

I think there is an error in your config.json
The error states that a comma is missing in line 11 (after the string with your cluster callsign)
Please compare the structure of your file with the template:
https://github.com/coulisse/spiderweb/blob/master/cfg/config.json.template

73 Joe, OE5JFE (from the SOTA Reflector)

**Comment by 9M2PJU** [comment]
i have found new problem. nothing from dx spider writes to mariadb. tried many config as suggested from dx spider mailing list but nothings work.

# the SQL database DBI dsn

$dsn = "dbi:mysql:dbname=dxcluster";

$dbuser = "sysop";

$dbpass = "password";

# the SQL database DBI dsn

$dsn = "dbi:mysql:dxcluster:localhost:3306";

$dbuser = "sysop";

$dbpass = "password";

**Comment by DocViper666** [comment]
Did you create the database and tables on your mysql server?
The automatic creation of the table did not work for me.

So here the sql script to create it:
https://github.com/DocViper666/dxspider-deployment/blob/master/cluster-db/init/create_new_db.sql

**Comment by 9M2PJU** [comment]
i have already create tables with this https://github.com/DocViper666/dxspider-deployment/blob/master/cluster-db/init/create_new_db.sql

and create user and grand all privilleges.
and set DXVars.pm to

# the SQL database DBI dsn
$dsn = "dbi:mysql:dxcluster:localhost:3306";
$dbuser = "sysop";
$dbpass = "password";

but nothing writes to the database

**Comment by wifi75** [comment]
> Did you create the database and tables on your mysql server? The automatic creation of the table did not work for me.
> 
> So here the sql script to create it: https://github.com/DocViper666/dxspider-deployment/blob/master/cluster-db/init/create_new_db.sql

hello I trieded to import file create_new_db.sql with phpmyadmin but there is this problem..

![image](https://github.com/coulisse/spiderweb/assets/31816231/2feee7bd-f844-49f6-b54b-1ee8d0bf4fab)

how I can fix?

**Comment by DocViper666** [comment]
I only see warnings and no error. So I guess it should be fine.
And it would be good to changes to English user interface for the screenshot - at least for me to understand what the error says.
 
Did you check if now the database dxcluster exists?
And it should have a table named "spot".
You can display that in phpadmin

**Comment by wifi75** [comment]
> I only see warnings and no error. So I guess it should be fine. And it would be good to changes to English user interface for the screenshot - at least for me to understand what the error says.
> 
> Did you check if now the database dxcluster exists? And it should have a table named "spot". You can display that in phpadmin

there is terminal after command: python3 webapp.py

![image](https://github.com/coulisse/spiderweb/assets/31816231/0842acf8-e214-4db5-9397-4f063a5dba8c)

from the web typing ip:5000 there is an error
![image](https://github.com/coulisse/spiderweb/assets/31816231/2e8c4161-d23e-4d14-bfee-39c1081ba08f)

below golder location
![image](https://github.com/coulisse/spiderweb/assets/31816231/eeb7ccc4-3ea2-4e49-a3ba-d6fc3d63b57b)

**Comment by DocViper666** [comment]
The error message states that there is no data in the database. So start your DXspider on a terminal. Log into your dxcluster by telnet and create a test spot. This way you should have at least one data entry in your database.
To check if the connection works have a look in the debug log file within /spider/

**Comment by wifi75** [comment]
and this error:

![image](https://github.com/coulisse/spiderweb/assets/31816231/95485234-64be-4174-8356-460666fca03f)

**Comment by DocViper666** [comment]
Did you follow the readme?
https://github.com/coulisse/spiderweb#configuration
You will need to create the config file based on the template.

**Comment by wifi75** [comment]
> Did you follow the readme? https://github.com/coulisse/spiderweb#configuration You will need to create the config file based on the template.

sure:

![image](https://github.com/coulisse/spiderweb/assets/31816231/bca54501-07c0-4ef4-b817-fc1959c28eda)

![image](https://github.com/coulisse/spiderweb/assets/31816231/ea0433d2-1e25-420f-af3c-291e2c9c523a)

**Comment by DocViper666** [comment]
See my updated comment. No issues with the error. It looks in two folders and found it in the second one.

**Comment by wifi75** [comment]
a question, because in the present guide it is not clear, but where should the spiderweb folder be copied?

**Comment by DocViper666** [comment]
No specific place in general. As long as it can reach the database it does not matter.

I use a docker container with bjorn to deploy it

**Comment by coulisse** [comment]
I close this issue since is not related to spiderweb but to Dxspider.
I'm thinking to switch to Sqllite in next versions
