### ISSUE TITLE
Error when starting webapp.py

### ISSUE THREAD

**Issue by 9M2PJU** [coulisse/spiderweb#57]
I dont know how to solve this 

<img width="1273" alt="image" src="https://github.com/coulisse/spiderweb/assets/991353/2020ad0f-b7c2-4a5f-8dca-1dbd716eed1f">

nothing showed on IP:5000

**Comment by coulisse** [comment]
Could you attach the log files in the folder "log"?

**Comment by coulisse** [comment]
“Closing this issue due to lack of recent activity. Feel free to reopen if needed.”
