### ISSUE TITLE
Protect plots.html

### ISSUE THREAD

**Issue by s50u** [coulisse/spiderweb#69]
Due to the dxtelnet module it's mandatory to protect plots.html to blocks IP addresses or http clients that make an unusually high number of concurrent requests or that make a large number of requests over small period of time. 🤔

Thanks, Dan S50U

**Comment by coulisse** [comment]
Sorry, but I don't understand.. please, could you explain me well? Thanks!!!

**Comment by s50u** [comment]
----- Dne 29. Nov. 2024 ob 10:21 je Corrado Gerbaldo ***@***.***> napisal(a): 




Sorry, but I don't understand.. please, could you explain me well? Thanks!!! 


Although too many simultaneous queries are supposed to be handled by the firewall (DoS attacks and the like). 
I experienced that a "user" in my case S53IXY-8 was constantly connecting through the spiderweb application and I had to block him several times. I have the Telegram BOT application configured to notify me of too frequent reconnects to DXCluster where I noticed problems there of constant reconnects every few seconds. As a precaution it might be worth considering additional protection against frequent calls of the plots.html page or refreshing it by "bots". 

Ciao, Danilo S50U

**Comment by s50u** [comment]
Or adding a password for the dxtelnet module user on both sides as a first security approach and a very good mandatory solution. 73s Dan S50U

**Comment by coulisse** [comment]
Instead to call a Telnet connection every time the plot page is opened, I think I schedule every 15 minutes a telnet connection and the plot page will reads these data.
Do you think this is  ok for you?

**Comment by s50u** [comment]
Maybe even try a smaller time interval of say 5 minutes? Any comments from other interested on this topic? 😕

**Comment by coulisse** [comment]
Solved with release  [v2.5.7](https://github.com/coulisse/spiderweb/releases/tag/v2.5.7)
