### ISSUE TITLE
Difference to nodes/users 

### ISSUE THREAD

**Issue by videobuff** [coulisse/spiderweb#74]
I finally managed the installation.
OS server is Debian 12
Database is Mariadb
proxy server is nginx.

[](adres is https://dxcluster.pa0esh.nl)

However, if i give the command `who `at dxspider and look at the 2nd page of the coulisse site at the nodes and users, there is a differance.

See the pictures. Top is coulisse, bottom is telnet.

<img width="536" alt="Scherm­afbeelding 2024-10-11 om 00 31 47" src="https://github.com/user-attachments/assets/8941d5b8-6c45-4a14-b3b1-6da4cec66cf9">
<img width="568" alt="Scherm­afbeelding 2024-10-11 om 00 31 39" src="https://github.com/user-attachments/assets/3d628ebc-30d5-47a8-ab38-b2a8067f4dfe">

Can anyone explain.

73's Erik

**Comment by maserowik** [comment]
were you albe to solve this issue?

Mike- N3BSQ

**Comment by coulisse** [comment]
Connecting to your website now I see:

![image](https://github.com/user-attachments/assets/70641780-76ed-4626-b051-dd0372af9d24)


If you do a `who` what do you see?

**Comment by coulisse** [comment]
Since there are not any news, I close this issue.
If  further help is needed, please reopen it.
