### ISSUE TITLE
Plots & Stats

### ISSUE THREAD

**Issue by maserowik** [coulisse/spiderweb#80]
so on my plots&stats I have the following showing up

![image](https://github.com/user-attachments/assets/e8013abc-2592-47f5-b227-fd325a82770d)

but doing a who on my cluster I have this 
![image](https://github.com/user-attachments/assets/47e7d832-305f-4987-932a-08b41fe6d760)

doing a  show/conn
![image](https://github.com/user-attachments/assets/28b003eb-5d03-4fd2-a5b3-6448f73981f0)

notice on the dxcluster who and show/conn command I have **9m2pju-2** showing up but that call is missing on the plots& stats web page.

Thanks
Mike- N3BSQ

**Comment by s50u** [comment]
> notice on the dxcluster who and show/conn command I have 9m2pju-2 showing up but that call is missing on the plots& stats web page.

In webapp.py change the parameter **TIMER_WHO = 2 * 60** and you will have fresher user data. The module will connect to the cluster every two minutes and retrieve users. Currently it is ten minutes by default.

HNY 2025 Dan S50U

**Comment by maserowik** [comment]
> > notice on the dxcluster who and show/conn command I have 9m2pju-2 showing up but that call is missing on the plots& stats web page.
> 
> In webapp.py change the parameter **TIMER_WHO = 2 * 60** and you will have fresher user data. The module will connect to the cluster every two minutes and retrieve users. Currently it is ten minutes by default.
> 
> HNY 2025 Dan S50U

In the config.sh I have the spot set to refresh 1000    

![image](https://github.com/user-attachments/assets/e565b8fa-3000-47cf-bb4a-ba3eb624944b)

**Comment by s50u** [comment]
> In the config.sh I have the spot set to refresh 1000

Mike
The refresh time of the spots has no relation to the user&node list. A security enhancement for the telnet connection to retrieve the WHO list is written in /spiderweb/docs. Check issues #69 acording to link below.

Date: 22/12/2024
Release: v2.5.7
- Improved telnet connection - Issue [#69](https://github.com/coulisse/spiderweb/issues/69)

**Comment by maserowik** [comment]
I am currently  on 2.5.7.  According to the release docs this issue is solved?   Now I am confused.  The is not a user it is a dx node.Michael A. SerowikSent from my iPhoneOn Dec 26, 2024, at 4:09 PM, s50u ***@***.***> wrote:﻿

In the config.sh I have the spot set to refresh 1000

Mike
The refresh time of the spots has no relation to the user&node list. A security enhancement for the telnet connection to retrieve the WHO list is written in /spiderweb/docs. Check issues #69 acording to link below.
Date: 22/12/2024
Release: v2.5.7

Improved telnet connection - Issue #69

**Comment by s50u** [comment]
> I am currently  on 2.5.7.  According to the release docs this issue is solved?   Now I am confused.  The is not a user it is a dx node.

I found the problem.
Very the first line of the dxspider WHO command is ignored. It will need finishing by the author in the next release.

HNY 2025, Dan S50U

**Comment by coulisse** [comment]
Thanks for your debug, I'll work on it

**Comment by coulisse** [comment]
Hello
I committed on "development" brach a new version, in order to fix this issue? Could anyone make any further tests?

**Comment by maserowik** [comment]
Thanks I was away for  Christmas and just did the update and it is working correctly. 
 
![image](https://github.com/user-attachments/assets/cc229687-0465-4e52-aee7-c27993b073ea)
